### ISSUE TITLE
Configure/fix board orientation

### ISSUE THREAD

**Issue by audio-engineer** [audio-engineer/chess-teacher-front-end#67]
When a game is running, the black player should see the board upside down, while the white player should keep the current board orientation.

As for selecting a color, there are two options:
1. Assume that no games are running and the first player logs in - they should be able to open a new game from the lobby and select which color they want to play. When another player logs in, they should be forced to play the other side.
2. A color is chosen at random when the first player opens a new game.

**Comment by Danar435** [comment]
Closing this due to it now being fixed thanks to Martin's changes
